### ISSUE TITLE
Optional support for JPEGmini

### ISSUE THREAD

**Issue by paleite** [allbitsnbytes/gulp-imageoptim#2]
Hi!
I really love your tool and it works really well, but if possible, I'd also like optional support for JPEGmini as that's the one feature I feel missing.

Are there any plans on integrating that?

**Comment by allbitsnbytes** [comment]
Hi Paleite,

I didn't have any plans to support JPEGmini.  However, since you've brought it up I'll consider it.

**Comment by paleite** [comment]
Perfect, thanks! :+1:

**Comment by JamesJosephFinn** [comment]
+1 for JPEG Mini. It's the best for .jpg optimization. Great tool, by the way!

**Comment by terryupton** [comment]
+1 for JPEG Mini. Would be awesome.
