### ISSUE TITLE
Optimize image simultaneously

### ISSUE THREAD

**Issue by almone** [allbitsnbytes/gulp-imageoptim#4]
How do I optimize images simultaneously?
Right now they optimizing one by one which takes very long time.

I run the following task from my gulpfile.js:

```
// `gulp imageoptim` - Run lossless compression on all the images.
gulp.task('imageoptim', function() {
  return gulp.src(globs.images)
    .pipe(imageOptim.optimize())
    .pipe(gulp.dest(path.dist + 'images'))
    .pipe(browserSync.stream());
});
```

**Comment by allbitsnbytes** [comment]
I've added bulk optimization.  Update to version 0.3.1 from the NPM repository.   Let me know if you experience any issues.
