### ISSUE TITLE
Stream Support?

### ISSUE THREAD

**Issue by huphtur** [allbitsnbytes/gulp-imageoptim#5]
Handing over a resized imaged to imageOptim (in the same stream) don't seem to work (example below works fine with [imagemin](https://github.com/sindresorhus/gulp-imagemin)). Any suggestions how to resolve this? Or should I look into [task dependency](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md)?

``` javascript
gulp.task('images', function() {
  return gulp.src('src/images/**/*')
    .pipe(imageResize({
      width: "50%"
    }))
    .pipe(imageOptim.optimize())
    .pipe(gulp.dest('build/images'));
});
```

**Comment by allbitsnbytes** [comment]
Thanks for pointing out that issue.  It's been fixed, 0.3.5.

**Comment by huphtur** [comment]
Still not working for me with 0.3.5.  :cry:

**Comment by allbitsnbytes** [comment]
I tested using gulp-image-resize and it's working fine for me.  Are you getting an error message?  What is it?

**Comment by huphtur** [comment]
Set up a separate test case and now things work! I must have done something weird in my original recipe. Thank you sir. Have a great 2016!
